// Generated by pandoc-stuff/convert_all.py. Do not edit by hand.
export const generatedPosts = [
  {
    "slug": "brauer-groups",
    "title": "Brauer Group",
    "date": "April 2026",
    "excerpt": "An introduction to Brauer groups, first for a field (i.e., Spec k for a geometer) and then for a scheme.",
    "tags": [
      "Algebra",
      "Algebraic Geometry"
    ]
  },
  {
    "slug": "representation-theory",
    "title": "Representation Theory",
    "date": "June 2025",
    "excerpt": "Basics on the representation of complex semisimple Lie algebras, with some examples worked out.",
    "tags": [
      "Algebra"
    ]
  },
  {
    "slug": "beilinson",
    "title": "Beilinson's Resolution of the Diagonal",
    "date": "April 2025",
    "excerpt": "An explanation of Beilinson's famous 'Problems in Linear Algebra', in particular showing how his paper gives a full strong exceptional collection and a derived equivalence to quiver representations.",
    "tags": [
      "Algebraic Geometry",
      "Category Theory"
    ]
  },
  {
    "slug": "tilting",
    "title": "Tilting",
    "date": "March 2025",
    "excerpt": "An introduction to the machinery of tilting sheaves for writing down derived equivalences. In particular, we compute the functors explicitly in some examples.",
    "tags": [
      "Algebra",
      "Category Theory"
    ]
  },
  {
    "slug": "stability-conditions",
    "title": "Stability Conditions",
    "date": "October 2024",
    "excerpt": "An introduction to Bridgeland stability, which, granted, doesn't get much farther than discussing t-structures.",
    "tags": [
      "Algebraic Geometry",
      "Category Theory"
    ]
  },
  {
    "slug": "syzygies",
    "title": "Syzygies in Algebraic Geometry",
    "date": "August 2024",
    "excerpt": "An introduction to syzygies and minimal free resolutions in the context of algebraic geometry, with an emphasis on Castelnuovo-Mumford regularity.",
    "tags": [
      "Algebraic Geometry"
    ]
  },
  {
    "slug": "variations-of-hodge-structures",
    "title": "Variations of Hodge Structures",
    "date": "April 2024",
    "excerpt": "A note on how families of complex manifolds give rise to a 'variation of hodge structures'. Along the way, we compute the monodromy representation on cohomology for the Legendre family.",
    "tags": [
      "Algebraic Geometry"
    ]
  },
  {
    "slug": "nullstellensatz",
    "title": "Nullstellensatz",
    "date": "July 2022",
    "excerpt": "Hilbert's Nullstellensatz bridges algebra and geometry. This article develops commutative algebra before arriving at a proof.",
    "tags": [
      "Algebra"
    ]
  }
];
